# Name of workflow
name: Render Deploy

# Trigger workflow on push to main branch
on:
  push:
    branches: [main]

# Jobs to carry out
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install dependencies and run tests
      - name: Test
        run: |
          npm install
          npm run test-component

      # Trigger Render Deploy
      - name: Deploy
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$DEPLOY_URL"
